### ISSUE TITLE
What endpoints are you using?

### ISSUE THREAD

**Issue by lodenrogue** [ropenscilabs/dbhydroR#4]
What endpoints are you using to get your data? Are you scraping the dbhydro browser directly or are there some specific endpoints you're calling?

Thanks

**Comment by jsta** [comment]
I'm using the `httr` package to scrape the DBHYDRO browser using the API outlined in the `URL-BASED DATA ACCESS` section (3.0) in the [DBHYDRO User's Guide](http://www.sfwmd.gov/portal/page/portal/xrepository/sfwmd_repository_pdf/dbhydrobrowseruserdocumentation.pdf).

**Comment by lodenrogue** [comment]
Do you feel like there would be value in having proper endpoints so you don't have to scrape? In case the UI changes in the future?

**Comment by jsta** [comment]
I think there would be value. What kind of UI change do you think would break `dbhydroR`? The automated testing suite should catch big changes...

**Comment by lodenrogue** [comment]
I'm not sure how you're extracting the data but if the html or css selectors change (traditionally in web scraping projects) then the library may break. I think having a proper and well constructed REST API may be the best solution for this library.

**Comment by jsta** [comment]
Closing pending any SFWMD API development
